### ISSUE TITLE
这个对系统有要求吗，WIN11+Python3.8为什么环境创建都很困难

### ISSUE THREAD

**Issue by yungongzi** [gisgyf/OMGD#2]
这个对系统有要求吗，WIN11+Python3.8为什么环境创建都很困难

**Comment by gisgyf** [comment]
配置环境对系统没有要求呀，Python版本>=3.7且<3.11应该都没问题。以下以pycharm平台为例，展示两种构建环境的方法：


**1. Python直接构建**
首先使用pycharm打开文件夹，右下角添加解释器（新的虚拟环境，无需继承全局包），选择一个基础解释器。
![image](https://github.com/user-attachments/assets/03e27046-9c8c-412b-974d-c62819341a03)

随后打开pycharm中右下角的终端（terminal），使用pip安装0.41.2版本的wheel，最后使用pip install -r requirements.txt安装依赖项即可。
![image](https://github.com/user-attachments/assets/98d1264c-4fdb-4d09-a9ee-c5796fd4796e)


**2. Conda环境构建**
首先打开omgd.yml，将prefix地址修改为你计算机中Anaconda的地址：Anaconda文件夹/envs/omgd
![image](https://github.com/user-attachments/assets/6f821f34-4ff5-4163-9843-03d5ceeeb534)

随后打开anaconda promt，输入“conda env create -f omgd.yml -n omgd”，安装完成后，输入conda env list，应当能看到名为omgd的环境，最后打开pycharm，添加解释器（系统解释器）即可（路径为omgd环境下的python.exe）
![image](https://github.com/user-attachments/assets/9606d4be-af4e-410d-9311-d50cc4e412d2)


祝你配置环境顺利，如果后续遇到什么问题，可以随时向我提出~
